### ISSUE TITLE
./lunar.sh: 行 60: 09: 数值太大不可为算数进制的基 (错误符号是 "09")

### ISSUE THREAD

**Issue by 0312birdzhang** [snowsolf/lunar#1]
./lunar.sh 20150908
./lunar.sh: 行 60: 09: 数值太大不可为算数进制的基 (错误符号是 "09")
Lunar date: 4711-11-18
Zodiac: Horse

**Comment by snowsolf** [comment]
已经解决了，谢谢支持！

**Comment by 0312birdzhang** [comment]
多谢!
